ShopAvto/ViewModels/CarsListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ShopAvto.Data.Models;

namespace ShopAvto.ViewModels
{
    public class CarsListViewModel
    {
        public IEnumerable<Car> allCars { get; set; }//получает все товары
        public string CurrentCategory { get; set; }//текущая категория с кот работаем
    }
}

ShopAvto/ViewModels/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ShopAvto.Data.Models;

namespace ShopAvto.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Car> favCars { get; set; }
    }
}

ShopAvto/ViewModels/ShopCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ShopAvto.Data.Models;

namespace ShopAvto.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart ShopCart { get; set; }
    }
}

ShopAvto/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShopAvto.Data.Interfaces;
using ShopAvto.Data.Models;
using ShopAvto.ViewModels;

namespace ShopAvto.Controllers
{
    public class CarsController : Controller
    {
        private readonly IAllCars allCars;
        private readonly ICarsCategory carsCategory;

        public CarsController(IAllCars iallCars, ICarsCategory icarsCategory)
        {
            allCars = iallCars;
            carsCategory = icarsCategory;
        }

        [Route("Cars/List")]   //здесь указ тот url, при переходе на кот будет срабат этот метод
        [Route("Cars/List/{category}")]
        public ViewResult List(string category)
        {
            //ViewBag.Category = "Some New";//для передачи данных внутрь html-шаблона (Category = "Some New")-любое название и его значение-любое
            //не рекомендуется исп тк для каждого значения новый viewbag
            //var cars = allCars.cars;//через интерфейс обращ к методу IEnumerable<Car> cars
            //return View(cars);

            string _category = category;
            IEnumerable<Car> cars = null;//присвоить значение чтоб внизу без ошиб
            string curCategory = "";
            if (string.IsNullOrEmpty(category))
            {
                cars = allCars.cars.OrderBy(i => i.Id);//сортируем по id
            }
            else
            {//если строка равна электро + не учитываем регистры
                if (string.Equals("electro", category, StringComparison.OrdinalIgnoreCase))
                {
                    cars = allCars.cars.Where(i => i.Category.CategoryName.Equals("Электромобили")).OrderBy(i => i.Id);
                    curCategory = "Электромобили";//присваиваем название для категории
                }
                else if (string.Equals("fuel", category, StringComparison.OrdinalIgnoreCase))
                {
                    cars = allCars.cars.Where(i => i.Category.CategoryName.Equals("Классические автомобили")).OrderBy(i => i.Id);
                    curCategory = "Классические автомобили";//присваиваем название для категории
                }

                
            }

            var carObject = new CarsListViewModel
            {
                allCars = cars,
                CurrentCategory = curCategory
            };

            ViewBag.Title = "Страница с автомобилями";
            //CarsListViewModel obj = new CarsListViewModel();
            //obj.allCars = allCars.cars;
            //obj.CurrentCategory = "Автомобили";

            return View(carObject);
        }
    }
}

ShopAvto/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShopAvto.Data.Interfaces;
using ShopAvto.ViewModels;

namespace ShopAvto.Controllers
{
    public class HomeController : Controller
    {
        private IAllCars CarRepository;
      
        public HomeController(IAllCars carRepository)
        {
            CarRepository = carRepository;          
        }

        public ViewResult Index()
        {
            var homeCars = new HomeViewModel
            {
                favCars = CarRepository.getFavCars
            };
            return View(homeCars);//все товары кот долж отобр на гл стр
        }
    }
}

ShopAvto/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShopAvto.Data.Interfaces;
using ShopAvto.Data.Models;

namespace ShopAvto.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;

        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }

        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]//отправка post --при завершении заказа вызовется метод
        public IActionResult Checkout(Order order)
        {
            shopCart.shopCartItems = shopCart.getShopItems();
            if(shopCart.shopCartItems.Count==0)
            {
                ModelState.AddModelError("", "У вас должны быть товары!");//указ ключ(здесь пустой) и сообщение 
            }

            if(ModelState.IsValid)
            {
                allOrders.CreateOrder(order);
                return RedirectToAction("Complete");
            }

            return View(order);//форма неверная но данные в ней сохранятся после перезагрузки страницы
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Заказ успешно обработан";
            return View();
        }
    }
}

ShopAvto/Controllers/ShopCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShopAvto.Data.Interfaces;
using ShopAvto.Data.Models;
using ShopAvto.Data.Repository;
using ShopAvto.ViewModels;

namespace ShopAvto.Controllers
{
    public class ShopCartController : Controller
    {
        private IAllCars CarRepository;
        private readonly ShopCart ShopCart;


        public ShopCartController(IAllCars carRepository, ShopCart shopCart)
        {
            CarRepository = carRepository;
            ShopCart = shopCart;
        }

        public ViewResult Index()
        {
            var items = ShopCart.getShopItems();
            ShopCart.shopCartItems = items;

            var obj = new ShopCartViewModel
            {
                ShopCart = ShopCart
            };

            return View(obj);
        }

        //переадресация на др строницу и доб тов в корз
        public RedirectToActionResult AddToCart(int id) //int id == asp-route-id(id-название )
        {
            //перем-я выб нужный товар из списка всех товаров по id
            var item = CarRepository.cars.FirstOrDefault(i => i.Id == id);

            if(item!=null)
            {
                ShopCart.AddToCart(item);
            }
            return RedirectToAction("Index");//переадресация
        }
    }
}

ShopAvto/Views/Cars/List.cshtml
<h2>Все автомобили</h2>
@*<h3>@ViewBag.Category</h3>*@
<h3>@Model.CurrentCategory</h3>
<div class="row mt-5 mb-2">
    @{
        foreach (Car car in Model.allCars)
        {
            @Html.Partial("AllCars", car)
        }
    }
</div>

ShopAvto/Views/Home/Index.cshtml
@model HomeViewModel


<h2>Лучшие автомобили</h2>

<div class="row mt-5 mb-2">
    @{
        foreach (Car car in Model.favCars)
        {
            @Html.Partial("AllCars", car)
        }
    }
</div>

ShopAvto/Views/Order/Checkout.cshtml
@model Order

<div class="row">
    <h3>Оформление заказа</h3>
    <form asp-action="Checkout" method="post" class="form-horizontal">
        <div class="form-group">
            <label asp-for="Name"></label>
            <div class="col-md-5">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Surname"></label>
            <div class="col-md-5">
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address"></label>
            <div class="col-md-5">
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Phone"></label>
            <div class="col-md-5">
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email"></label>
            <div class="col-md-5">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <input class="btn btn-success" type="submit" value="Завершить заказ" />
    </form>
</div>

ShopAvto/Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

ShopAvto/Views/Shared/AllCars.cshtml
@model Car

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.Img" alt="@Model.Name" />
    <h2>@Model.Name</h2>
    <p>@Model.ShortDescription</p>
    <p>Цена: @Model.Price.ToString("c")</p>@*преобразует в денежный формат*@
    <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="AddToCart" asp-route-id="@Model.Id">Добавить в корзину</a></p>
</div>

ShopAvto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/Style.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">          
                <a class="navbar-brand" href="#">KATURENE</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item active">
                            @*далее используем тег хелперы подключаются в ViewImports
                            <a class="nav-link" href="/">Главная</a>*@
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List">Машины</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List/electro">Электро</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link" href="/Cars/List/fuel">Бензиновые</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/ShopCart/">Корзина</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="text" placeholder="Поиск" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Поиск</button>
                    </form>
                </div>           
        </nav>
    </header>
    <div class="container mt-5"> @*прописать чтоб блоки были по центру и отступ сверху*@
        @RenderBody()
    </div>
    <footer class="container">
        <p class="float-end"><a href="#">Back to top</a></p>
        <p>© 2021 Katurene, Inc.  <a href="#">Privacy</a>  <a href="#">Terms</a></p>
    </footer>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>

ShopAvto/Views/ShopCart/Index.cshtml
@model ShopCartViewModel

<div class="container">
    @foreach(var el in Model.ShopCart.shopCartItems)
    {
        <div class="alert alert-warning mt-3">
            <b>Автомобиль:</b> @el.Car.Name <br />
            <b>Цена:</b> @el.Car.Price.ToString("c")
        </div>
    }
    <hr />
    <a class="btn btn-danger" asp-controller="Order" asp-action="Checkout">Оплатить</a>
</div>